import './globals.css'
import { Outfit } from 'next/font/google'
import Navbar from './components/navbar/navbar'
import Footer from './components/footer/footer'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className='container'>
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  )
}
